### ISSUE TITLE
Kaitai Struct

### ISSUE THREAD

**Issue by treiher** [Componolit/message-sequence-formalization#4]
http://kaitai.io/

**Comment by ManuelNetz** [comment]
[Documentation](https://doc.kaitai.io/user_guide.html)

Is able to express the following (list) constructs:

1. https://github.com/Componolit/systematization-binary-schemas/issues/6
2. https://github.com/Componolit/systematization-binary-schemas/issues/7
3. https://github.com/Componolit/systematization-binary-schemas/issues/8
4. https://github.com/Componolit/systematization-binary-schemas/issues/9
5. https://github.com/Componolit/systematization-binary-schemas/issues/13
6. https://github.com/Componolit/systematization-binary-schemas/issues/29
7. https://github.com/Componolit/systematization-binary-schemas/issues/30



# Examples:

**For 1.& 2.:**
```
meta:
  id: example
  endian: be
seq:
  - id: length_field
    type: u1                     #8-bit unsigned int
  - id: var_field
    length: length_field
   -id: delimited_field
    type: str
    terminator: 0                #0x00
```

**For 3.:**

```
seq:
  - id: entryCount
    type: u4
  - id: enties
    type: entry
    repeat: expr
    repeat-expr: entryCounts

types:
    entry:
        seq:
            -id: ...
             #...
    someOtherType:
        #...
```

**Comment by ManuelNetz** [comment]
[**Message format 1**](https://github.com/Componolit/message-sequence-formalization/wiki/Test-message-format-1-(DNS-inspired)):
<details>

```
meta:
  id: format_1
  file-extension: format_1
  endian: le

seq:              #defines format as a sequence of fields
  - id: magic     #name of this field, can be used to reference elsewhere
    contents: [0x66, 0x6F, 0x72, 0x6D, 0x61 0x74 0x20 0x31]
  - id: count
    type: u1    #count of names in the following name array
  - id: name_array
    type: name                    #custom type; see types section
    repeat: expr                  #a repetition of names
    repeat-expr: count            #repeat 'count' times

types:
  name:
    seq:
      - id: name_length
        type: u1

      - id: name_value
        type: str
        size: name_length
        encoding: ASCII

```
</details>

> Has no problem parsing this format.

**[Format 3:](https://github.com/Componolit/message-sequence-formalization/wiki/Test-message-format-3)**

<details>

```
meta:
  id: format_3
  file-extension: format_3
  endian: be

seq:
  - id: length_field
    type: u1
  
  - id: some_disturbance
    type: u4
  
  - id: data_field
    type: str
    size: length_field
    encoding: ASCII

```
</details>

> Again, no problem parsing this

[**Format 4:**](https://github.com/Componolit/message-sequence-formalization/wiki/Test-message-format-4)

<details>

```
meta:
  id: format_4
  file-extension: format_4
  endian: be

seq:
  - id: magic
    size: 8
    contents: [0x66, 0x6F, 0x72, 0x6D, 0x61 0x74 0x20 0x34]
  - id: data
    type: u1
    repeat: until             #repeat until condition is met
    repeat-until: _ == 0x00   #condition; if parsed byte == 0x00 stop repeating

```
</details>

> Not as easy. The documentation suggest that you can use a terminator- attribute, but this didnt work in my tests. <br>
> This method works, but parses the terminating byte with value 0x00 as part of the data


[**Format 7:**](https://github.com/Componolit/message-sequence-formalization/wiki/Test-message-format-7)

<details>

```
 meta:
  id: format_7
  file-extension: format_7
  endian: be

seq:
  - id: core_length
    type: u1
    
  - id: core_format
    size: core_length        #creates a substream with limited size
    type: core_format

types:
  core_format:
    seq:
      - id: magic_bytes
        size: 8      #just consumes 8 byte without checking them, because i forgot
        
      - id: options
        repeat: eos         #matches options until this substream ends
        type: option
    
  option:
    seq:
      - id: option_type
        type: u1
      - id: option_length
        type: 
          switch-on: option_type   #decides if this is a normal option or the 'end of options' option
          cases:
            0xff: padding                #after otion 0xff only padding for rest of stream
            _: normal_option
      
  padding:
    seq:
      - id: padding        #only padding follows
        type: u1
        repeat: eos
        
  normal_option:
     seq:
        - id: option_length
          type: u1
        - id: option_data
          size: option_length

 ```

</details>

> The use of substreams makes this easy; A substream is created when you declare a size for a field.


[**Format 8:**](https://github.com/Componolit/message-sequence-formalization/wiki/Test-message-format-8)

> Kaitai Struct doesnt have a mechanism, that i am aware off, to keep track off global appeareces of fields and thus cannot assure that a field doesn't appear multiple times. <br>
> There is the possibility to encode every possible permutation and test if one of those matches .... but that is impossible for larger messega formats

[**Format 2:**](https://github.com/Componolit/message-sequence-formalization/wiki/Test-message-format-2-(IPv4-inspired))

> Cannot handle this format. <br>
> You can create substreams of variable length and you can use an optional terminator to stop parsing this field, but Kaitai Struct assumes that this field is still the original length and not the shorter length the it should be by using a (optional) terminator.
